### ISSUE TITLE
DR_AI

### ISSUE THREAD

**Issue by saisaitian** [Barabasi-Lab/COVID-19#1]
In your script of DR_AI, the processed script of Dataset 6 and Dataset 7 was not shown in this. Could you share with us? In addition, the Diffusion script could be written in R language? In fact, I am not good at python

**Comment by hanxin108** [comment]
Excuse me, can you share how you obtained data set 6 and data set 7?

**Comment by deisygysi** [comment]
For the code to generate datasets 6 and 7 please see the https://github.com/mims-harvard/graphml-tutorials/tree/master/02-KG. It contains a full implementation of a graph neural network model and an example showing how the model can be applied to a biomedical knowledge graph of your choice.

**Comment by hanxin108** [comment]
Thank you for your reply! I'm very happy! Can you share with me again how you use the crank algorithm to merge and sort the 12 lists into a comprehensive ranking? I went to see the original author's code, but I still don't know how to do it, is raa. py code enough? I don't quite understand the code.

--------------原始邮件--------------
发件人："Deisy&nbsp;Gysi ***@***.***&gt;;
发送时间：2022年4月4日(星期一) 晚上11:46
收件人："Barabasi-Lab/COVID-19" ***@***.***&gt;;
抄送："韩鑫 ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [Barabasi-Lab/COVID-19] DR_AI (Issue #1)
-----------------------------------

 

 
Closed #1.
